spring.application.name=tienda con inventario

spring.datasource.url=jdbc:mysql://localhost:3306/tiendaInventario
spring.datasource.username=root
spring.datasource.password=Allende1977*
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8081

tienda.direccion=Calle Principal Marco Plaza, Támesis, Antioquia, Colombia
tienda.telefono=(+57)333 568 88 00
tienda.email=contacto@tienda.com

logging.level.org.springframework.security=DEBUG